---
- name: Add line 
  hosts: host1
  tasks:
    - name:  Create file1
      file: 
        path: /tmp/file1
        state: touch
        mode: u+x,g+wx

    - name: Create file2 
      file: 
        path: /tmp/file2
        state: touch