--- 
- name: Install and Start Apache
  hosts: all
  tasks:
    - name: Inatall Apache
      yum:
        name: httpd
        state: installed
    - name: Start Apache
      systemd:
        name: httpd
        state: started
        enabled: yes