---
- name: Update package
  hosts: all
  gather_facts: yes
  become: yes
  tasks: 
    - name: Update Packages
      when: 
      - ansible_facts['distribution'] == "CentOS"
      - ansible_facts['distribution_major_version'] == "7"
      yum:
        name: '*'
        state: latest