---
all: #ungroup
  hosts: 
  children: 
    app: #user define group
      hosts:
        host1: #user defined host name
          ansible_host: 10.116.0.3
    database:
      hosts:
        host2:
          ansible_host: 10.116.0.4